/* Arbol de equipo de la maquina — Planta Tornquist. 3 niveles: Area > Subarea/Equipo > Equipo. Generado del arbol oficial. */
const ARBOL_EQUIPO = {
 "SERVICIOS AUXILIARES": {
  "BOMBAS AGUA POZO": [
   "BOMBA POZO 1",
   "BOMBA POZO 2",
   "BOMBA POZO 3",
   "BOMBA POZO 4",
   "BOMBA POZO 5",
   "BOMBA POZO 6"
  ],
  "TRATAMIENTO DE AGUA CALDERAS": [
   "BOMBA AGUA 505 DESCARBONATADORA CALDERAS",
   "BOMBA AGUA 506 DESCARBONATADORA CALDERAS",
   "BOMBA AGUA 507 ALIMENTACION TORRES CALDERAS",
   "BOMBA AGUA 508 ALIMENTACION TORRES CALDERAS",
   "BOMBA 509 DESAIREADOR CALDERAS",
   "BOMBA 510 DESAIREADOR CALDERAS",
   "BOMBAS DOSIFICADORAS PRODUCTOS QUIMICOS CALDERAS"
  ],
  "TRATAMIENTO EFLUENTES SECUNDARIO": [
   "BOMBA BS01 LODOS SEDIMENTADOR TSE",
   "BOMBA BS02 LODOS SEDIMENTADOR TSE",
   "PRENSA EMECAN TSE",
   "CINTA DE LODOS TSE LONGITUDINAL",
   "CINTA DE LODOS TSE TRANSVERSAL",
   "BOMBA PILETA LODOS TSE",
   "AGITADOR TQ UREA TSE",
   "AGITADOR TQ FLOCULANTE TSE",
   "BOMBA TQ UREA TSE",
   "BOMBA TQ FLOCULANTE TSE",
   "SOPLADOR PILETA REACTIVACION TSE",
   "BOMBA REGADERA PRENSA EMECAN TSE",
   "DECANTADOR SECUNDARIO TSE",
   "SOPLADOR PIL AIREACION TSE",
   "SOPLADOR PIL CLORACION TSE",
   "CONTIPRESS"
  ],
  "CALDERA 4": [
   "VTF CALDERA 4",
   "BOMBA AGUA 501 ALIMENTACION CALDERA 4",
   "BOMBA AGUA 502 ALIMENTACION CALDERA 4",
   "BOMBA FUEL OIL 1 CALDERA 4",
   "BOMBA FUEL OIL 2 CALDERA 4",
   "VAPOR CALDERA 4",
   "QUEMADOR CALDERA 4"
  ],
  "SALA COMPRESORES": [
   "COMPRESOR SULLAIR CS01",
   "COMPRESOR SULLAIR CS02",
   "COMPRESOR KAESER",
   "EQUIPO SECAIRE KAESER"
  ],
  "SUBESTACION TRANSFORMACION ELECTRICA": [],
  "GRUPO GENERADOR ELECTRICO": [],
  "PTA GAS": [],
  "PTA FUEL OIL": [],
  "GUILLOTINA JOVAL": []
 },
 "PULPERS": {
  "PULPER D30": [
   "PULPER D30",
   "CINTA DE CARGA PULPER D30",
   "TROMMEL PULPER D30",
   "FIBERIZER PULPER D30",
   "DEPURADOR 210 PULPER D30",
   "SAC A SAN PULPER D30",
   "BOMBA PULPER D30",
   "BOMBA TQ 200 D30",
   "AGITADOR TQ 200 D30"
  ],
  "PULPER E20": [
   "PULPER E20",
   "CINTA DE CARGA PULPER E20",
   "TROMMEL PULPER E20",
   "FIBERIZER PULPER E20",
   "BOMBA PULPER E20"
  ],
  "PULPER E21": [
   "PULPER E21",
   "CINTA DE CARGA PULPER E21",
   "BOMBA PULPER E21"
  ],
  "PULPER E22": [
   "PULPER E22",
   "CINTA DE CARGA PULPER E22",
   "TROMMEL PULPER E22",
   "FIBERIZER PULPER E22",
   "BOMBA PULPER E22"
  ],
  "ALMIDON PULPERS": [
   "BOMBA TQ COCINADOR ALMIDON",
   "BOMBA TQ ALMACENAMIENTO ALMIDON",
   "AGITADOR TQ COCINADOR ALMIDON",
   "AGITADOR TQ ALMACENAMIENTO ALMIDON",
   "MANIFOLD VAPOR ALMIDON"
  ]
 },
 "PLANTA DE PASTA": {
  "SECTOR REFINOS Y FIBERIZER": [
   "ZARANDA 102",
   "DESPASTILLADOR 301",
   "REFINADOR 303",
   "REFINADOR 102",
   "REFINADOR 101",
   "REFINADOR 301",
   "REFINADOR 201",
   "REFINADOR 302",
   "FIBERIZER 101",
   "FIBERIZER 301",
   "FIBERIZER 302",
   "DEPURADOR D1CA 301",
   "DEPURADOR D1CA 302",
   "DEPURADOR V12 CI",
   "FRACCIONADOR 220"
  ],
  "TEC MAULE PLANTA ALTA": [
   "SEPARPLAST 231",
   "SEPARPLAST 232",
   "ZARANDA SEPARPLAST",
   "BOMBA REGADERA SEPARPLAST",
   "TORNILLO ELEVACION TEC MAULE",
   "AGITADOR TQ 260",
   "AGITADOR TQ 100 DORSO"
  ],
  "TEC BLANES": [
   "PRENSA TELA TEC BLANES",
   "DISPERSOR TEC BLANES",
   "TORNILLOS TRANSPORTADORES TEC BLANES",
   "MANIFOLD VAPOR TEC BLANES",
   "DEPURADORES 1º CI",
   "DEPURADORES 2º CI",
   "DEPURADORES 3º CI",
   "DEPURADOR DP3",
   "FAN SEPARATOR"
  ],
  "CONTROLADORES": []
 },
 "TEC MAULE PTA BAJA": {
  "TANQUE AGUA CIRCULANTE": [
   "BOMBA DILUCION 1 TAC",
   "BOMBA DILUCION 2 TAC",
   "BOMBA DILUCION 3 TAC",
   "BOMBA DILUCION 4 TAC",
   "BOMBA DILUCION 5 TAC",
   "BOMBA DILUCION 6 TAC"
  ],
  "TANQUE 230": [
   "BOMBA TQ 230",
   "AGITADOR TQ 230"
  ],
  "TANQUE 250": [
   "BOMBA TQ 250",
   "AGITADOR TQ 250",
   "BOMBA RECIRCULACION TQ 250"
  ],
  "TANQUE 260": [
   "BOMBA TQ 260"
  ],
  "SAC A SAN SEPARPLAST": [],
  "BOMBA TQ 100 DORSO": []
 },
 "TAP": {
  "BOMBA ADT": [],
  "BOMBA 1 TQ AGUA A CLARIFICAR - DELTAFLOAT": [],
  "BOMBA 1 TQ AGUA CLARIFICADA - TQ243 Y TQ260": [],
  "BOMBA 1 TQ AGUA FILTRADA - PULPO CI": [],
  "BOMBA 2 TQ AGUA A CLARIFICAR - TAC": [],
  "BOMBA 2 TQ AGUA CLARIFICADA - SIGMAFILTER": [],
  "BOMBA 2 TQ AGUA FILTRADA - FIBERNET": [],
  "DELTAFLOAT DF47": [],
  "SIGMAFILTER": []
 },
 "PILETAS LM": {
  "PILETA 210": [
   "BOMBA PIL 210",
   "AGITADOR PIL 210"
  ],
  "PILETA 401": [
   "BOMBA PIL 401",
   "AGITADOR PIL 401"
  ],
  "PILETA 101": [
   "BOMBA PIL 101",
   "AGITADOR PIL 101"
  ],
  "PILETA B": [
   "BOMBA PIL B"
  ],
  "PILETA 3.5BAR": [
   "BOMBA PIL 3.5BAR"
  ],
  "PILETA A": [
   "BOMBA 01 PIL A",
   "BOMBA 02 PIL A"
  ],
  "BOMBA FILTROS RONNINGEN": [],
  "TANQUE ELEVACION": [
   "BOMBA 1 TQ ELEV",
   "BOMBA 2 TQ ELEV"
  ],
  "TINA TEC BLANES": [
   "BOMBA TINA TEC BLANES",
   "AGITADOR TINA TEC BLANES"
  ],
  "BOMBA DEPURACION 1º CI": [],
  "BOMBA DEPURACION 2º CI": [],
  "BOMBA DEPURACION 3º CI": [],
  "BOMBA DP3": [],
  "BOMBA TQ REBALSE DEP CI": [],
  "BOMBA PILETA AGUA CIRCULANTE": [],
  "BOMBA AUXILIAR CELLIER": [],
  "DEPURADOR V12 CUP": [],
  "DEPURADOR V22 CI": [],
  "BOMBA FAN CI": [],
  "BOMBA TANQUE 305": [],
  "BOMBA DEPURADOR DP2 CI": []
 },
 "PILETAS LC": {
  "PILETA 102": [
   "AGITADOR PIL 102"
  ],
  "PILETA 270": [
   "AGITADOR PIL 270"
  ],
  "PILETA 220": [
   "BOMBA PIL 220",
   "AGITADOR PIL 220"
  ],
  "PILETA 301": [
   "BOMBA PIL 301",
   "AGITADOR PIL 301"
  ],
  "PILETA 242": [
   "BOMBA PIL 242",
   "AGITADOR PIL 242"
  ],
  "PILETA 303": [
   "BOMBA PIL 303",
   "AGITADOR PIL 303"
  ],
  "PILETA 302": [
   "BOMBA PIL 302",
   "AGITADOR PIL 302"
  ],
  "PILETA 304": [
   "BOMBA PIL 304",
   "AGITADOR PIL 304"
  ],
  "PILETA 103": [
   "BOMBA PIL 103",
   "AGITADOR PIL 103"
  ],
  "AGENTES DE RETENCION": [
   "BOMBAS AGENTES DE RETENCION"
  ],
  "POLYMIN": [
   "BOMBAS POLYMIN"
  ]
 },
 "PILETA AGUA CORTE": {
  "PILETA AGUA CORTE": [
   "BOMBA AGUA REFILE POZO COUCH - VARIDUR",
   "BOMBA DILUCION PBM",
   "BOMBA MEZCLA PIL AGUA CORTE",
   "BOMBA AGUA CORTE POZO COUCH"
  ]
 },
 "TQ 200 CORTE": {
  "TANQUE 200 CORTE": [
   "BOMBA 1° NIVEL",
   "BOMBA 2° NIVEL",
   "AGITADOR"
  ]
 },
 "HIDROPOLIS": {
  "PLANTA ALTA": [
   "KROFTA",
   "DENSIDISC 1",
   "DENSIDISC 2",
   "ZARANDA 204",
   "ZARANDA 205",
   "ZARANDA 206"
  ],
  "PILETA ACUMULADORA": [
   "FIBERIZER PIL ACUM",
   "AGITADOR PIL ACUM",
   "BOMBA TITULAR PIL ACUM",
   "BOMBA AUXILIAR PIL ACUM",
   "BOMBA PIL PASTA RECUPERADA",
   "BOMBA TDA"
  ],
  "CANAL EFLUENTES": [
   "BOMBA EFLUENTES TITULAR",
   "BOMBA EFLUENTES AUXILIAR",
   "BOMBA EFLUENTES 3",
   "BOMBA SEDIFLOAT 1",
   "BOMBA SEDIFLOAT 2",
   "RASTRILLO"
  ],
  "TANQUE 450 EFLUENTES": [
   "BOMBA TIT TQ 450 EFLUENTES",
   "BOMBA AUX TQ 450 EFLUENTES",
   "AGITADOR TQ 450 EFLUENTES"
  ],
  "TANQUE 450 PASTA": [
   "BOMBA TQ 450 PASTA",
   "AGITADOR TQ 450 PASTA"
  ],
  "TANQUE 100 CUP": [
   "BOMBA TQ 100 CUP",
   "AGITADOR TQ 100 CUP"
  ]
 },
 "MESAS": {
  "SOTANO": [
   "BOMBA ALMIDON SPRAY 1",
   "BOMBA ALMIDON SPRAY 2",
   "BOMBA SEAL PIT CUP",
   "BOMBA PILETA 102",
   "BOMBA PILETA 270",
   "BOMBA V12 CUP",
   "BOMBA TQ REBALSE CUP",
   "BOMBA DEP PRIM DORSO",
   "BOMBA FAN DORSO",
   "BOMBA TQ BAJO TELA CUP",
   "BOMBA FAN CUP",
   "DEPURADOR V22 CUP",
   "BOMBA TQ RECIRC CUP",
   "BOMBA TQ RECHAZOS CUP",
   "BOMBA RECIRC DORSO",
   "BOMBA DEP SEC DORSO",
   "BOMBA RECUP DORSO",
   "BOMBA CORTE POZO COUCH",
   "DEPURADOR V22 DORSO",
   "BOMBA REFILE POZO COUCH",
   "AGITADOR POZO COUCH"
  ],
  "CUPERTINA": [
   "CAJA FORM MESA CUP",
   "CAJAS VACIO MESA CUP",
   "ROLLOS MESA CUP",
   "GUIA TELA MESA CUP",
   "TELA MESA CUP",
   "CUCHILLAS MESA CUP",
   "REGADERAS MESA CUP",
   "PISOR AUTOMATICO DE CORTE"
  ],
  "DORSO": [
   "CAJA FORM MESA DORSO",
   "CAJAS VACIO MESA DORSO",
   "ROLLOS MESA DORSO",
   "GUIA TELA MESA DORSO",
   "TELA MESA DORSO",
   "CUCHILLAS MESA DORSO",
   "REGADERAS MESA DORSO"
  ],
  "CAPA INTERMEDIA": [
   "CAJA FORM MESA CI",
   "CAJAS VACIO MESA CI",
   "ROLLOS MESA CI",
   "GUIA TELA MESA CI",
   "TELA MESA CI",
   "CUCHILLAS MESA CI",
   "REGADERAS MESA CI"
  ],
  "TOP FORMER": [
   "ROLLOS TOP FORMER",
   "GUIA TELA TOP FORMER",
   "TELA TOP FORMER",
   "CUCHILLAS TOP FORMER",
   "REGADERAS TOP FORMER"
  ],
  "MANDOS MESAS": [
   "MANDO M7 ROLLO TRANSF CI",
   "MANDO M4 RMT DORSO",
   "MANDO M8 ROLLO AUX. CI",
   "MANDO M5 ROLLO TRANSF DORSO",
   "MANDO M1 RMT CUP",
   "MANDO M2 ROLLO ASPIRANTE CUP",
   "MANDO M9 TOP FORMER",
   "MANDO M6 RMT CI"
  ],
  "DEPURADORES CENTRIFUGOS": [
   "DEPURADORES 1º DORSO",
   "DEPURADORES 2º DORSO",
   "DEPURADORES 1º CUPERTINA (DR2000)"
  ],
  "LOSA COMPRESORES MESAS": [
   "COMPRESOR CAJA MESA CI",
   "VENT BAJO VACIO CUP",
   "VENT BAJO VACIO DORSO",
   "VENT BAJO VACIO CI",
   "VENT BAJO VACIO AUXILIAR",
   "VENTILADORES TOP FORMER",
   "COMPRESOR CAJA MESA CUP",
   "VENT ENF MANDOS MESAS",
   "COMPRESOR CAJA MESA DORSO"
  ]
 },
 "PRENSAS": {
  "PRIMER PRENSA": [
   "ROLLOS 1º PRENSA",
   "GUIAS FIELTRO 1º PRENSA",
   "FIELTRO 1º PRENSA",
   "FUELLES NEU 1º PRENSA",
   "REGADERAS 1º PRENSA",
   "CUCHILLAS 1º PRENSA"
  ],
  "SEGUNDA PRENSA": [
   "ROLLOS 2º PRENSA",
   "GUIAS FIELTRO 2º PRENSA",
   "FIELTRO 2º PRENSA",
   "FUELLES NEU 2º PRENSA",
   "REGADERAS 2º PRENSA",
   "CUCHILLAS 2º PRENSA"
  ],
  "TEM SEC": [
   "ROLLOS TEM SEC",
   "GUIAS FIELTRO TEM SEC",
   "FIELTRO TEM SEC",
   "CENTRAL HIDRAULICA TEM SEC",
   "REGADERAS TEM SEC",
   "CUCHILLAS TEM SEC"
  ],
  "MANDOS PRENSAS": [
   "MANDO M10 1º PRENSA",
   "MANDO M11 2º PRENSA",
   "MANDO M12B TEMSEC 1º NIP",
   "MANDO M12A TEMSEC CIL BASE",
   "MANDO M12C TEMSEC 2º NIP",
   "CUCHILLAS TEM SEC"
  ]
 },
 "SECADORES": {
  "PRIMER BATERIA (1 AL 12)": [
   "SECADORES 1º BAT (1 AL 12)",
   "ROLLOS TELA 1º BAT",
   "MANDOS 1º BAT",
   "CUCHILLAS 1º BAT",
   "GUIA TELA 1º BAT SUP",
   "GUIA TELA 1º BAT INF",
   "TENSOR NEUM 1º BAT SUP",
   "TENSOR NEUM 1º BAT INF",
   "TENSOR MEC 1º BAT SUP",
   "TENSOR MEC 1º BAT INF",
   "TELA 1º BATERIA SUP",
   "TELA 1º BATERIA INF",
   "VAPOR SEC 1º BAT",
   "JRV SEC 1º BAT",
   "POLEAS DE SOGA 1º BAT",
   "TENSORES DE SOGA 1º BAT",
   "LUBRICACION 1º BAT"
  ],
  "SEGUNDA BATERIA (13 AL 24)": [
   "SECADORES 2º BAT (13 AL 24)",
   "ROLLOS TELA 2º BAT",
   "MANDOS 2º BAT",
   "CUCHILLAS 2º BAT",
   "GUIA TELA 2º BAT SUP",
   "GUIA TELA 2º BAT INF",
   "TENSOR NEUM 2º BAT SUP",
   "TENSOR NEUM 2º BAT INF",
   "TENSOR MEC 2º BAT SUP",
   "TENSOR MEC 2º BAT INF",
   "TELA 2º BATERIA SUP",
   "TELA 2º BATERIA INF",
   "VAPOR SEC 2º BAT",
   "JRV SEC 2º BAT",
   "POLEAS DE SOGA 2º BAT",
   "TENSORES DE SOGA 2º BAT",
   "LUBRICACION 2º BAT"
  ],
  "TERCER BATERIA (25 AL 35)": [
   "SECADORES 3º BAT (25 AL 35)",
   "ROLLOS TELA 3º BAT",
   "MANDOS 3º BAT",
   "CUCHILLAS 3º BAT",
   "GUIA TELA 3º BAT SUP",
   "GUIA TELA 3º BAT INF",
   "TENSOR NEUM 3º BAT SUP",
   "TENSOR NEUM 3º BAT INF",
   "TENSOR MEC 3º BAT SUP",
   "TENSOR MEC 3º BAT INF",
   "TELA 3º BATERIA SUP",
   "TELA 3º BATERIA INF",
   "VAPOR SEC 3º BAT",
   "JRV SEC 3º BAT",
   "POLEAS DE SOGA 3º BAT",
   "TENSORES DE SOGA 3º BAT",
   "LUBRICACION 3º BAT"
  ],
  "MONOLUCIDO": [
   "MONOLUCIDO",
   "ROLLOS MONOLUCIDO",
   "PRENSA MONOLUCIDO",
   "MANDO MONOLUCIDO",
   "CUCHILLAS MONOLUCIDO",
   "GUIA FIELTRO MONOLUCIDO",
   "FIELTRO MONOLUCIDO",
   "VAPOR MONOLUCIDO",
   "JRV MONOLUCIDO",
   "POLEAS DE SOGA MONOLUCIDO",
   "TENSORES SOGA MONOLUCIDO"
  ],
  "CUARTA BATERIA (36 AL 43)": [
   "SECADORES 4º BAT (36 AL 43)",
   "ROLLOS TELA 4º BAT",
   "MANDOS 4º BAT",
   "CUCHILLAS 4º BAT",
   "GUIA TELA 4º BAT SUP",
   "GUIA TELA 4º BAT INF",
   "TENSOR NEUM 4º BAT SUP",
   "TENSOR NEUM 4º BAT INF",
   "TENSOR MEC 4º BAT SUP",
   "TENSOR MEC 4º BAT INF",
   "TELA 4º BATERIA SUP",
   "TELA 4º BATERIA INF",
   "VAPOR SEC 4º BAT",
   "JRV SEC 4º BAT",
   "POLEAS DE SOGA 4º BAT",
   "TENSORES DE SOGA 4º BAT",
   "LUBRICACION 4º BAT"
  ],
  "QUINTA BATERIA (44 AL 53)": [
   "SECADORES 5º BAT (44 AL 53)",
   "ROLLOS TELA 5º BAT",
   "MANDOS 5º BAT",
   "CUCHILLAS 5º BAT",
   "GUIA TELA 5º BAT SUP",
   "GUIA TELA 5º BAT INF",
   "TENSOR NEUM 5º BAT SUP",
   "TENSOR NEUM 5º BAT INF",
   "TENSOR MEC 5º BAT SUP",
   "TENSOR MEC 5º BAT INF",
   "TELA 5º BATERIA SUP",
   "TELA 5º BATERIA INF",
   "VAPOR SEC 5º BAT",
   "JRV SEC 5º BAT",
   "POLEAS DE SOGA 5º BAT",
   "TENSORES DE SOGA 5º BAT",
   "LUBRICACION 5º BAT"
  ]
 },
 "BOMBAS DE VACIO": {
  "BOMBAS DE VACIO": [
   "BOMBA VACIO 01",
   "BOMBA VACIO 02",
   "BOMBA VACIO 03",
   "BOMBA VACIO 04",
   "BOMBA VACIO 05",
   "BOMBA VACIO 06",
   "BOMBA VACIO 07",
   "BOMBA VACIO 08",
   "BOMBA VACIO 09",
   "BOMBA VACIO 10",
   "BOMBA VACIO 11",
   "BOMBA VACIO 12",
   "BOMBA VACIO 13",
   "BOMBA SELLO VACIO",
   "BOMBA ELUTRIACION",
   "BOMBA SUMIDERO"
  ]
 },
 "PLANTA CONDENSADO": {
  "BOMBA VACIO BV-1": [],
  "BOMBA VACIO BV-2": [],
  "BOMBA BC3 TQ VACIO": [],
  "BOMBA BV4 TQ VACIO": [],
  "BOMBA BC5 TQ PULMON": [],
  "BOMBA BC6 TQ PULMON": []
 },
 "VENTILADORES Y EXTRACTORES": {
  "LOSA TALLER MECANICO": [
   "VENT AIRE CAL 4° y 5° BAT",
   "VENT EXTRACTOR CAPOTA 4° y 5° BAT",
   "VENT RECIRC II MONOLUCIDO",
   "VENT EXTRACTOR MONOLUCIDO",
   "VENT RECIRC I MONOLUCIDO",
   "VENT AIRE CAL 3° BAT",
   "VENT EXTRACTOR CAPOTA 3° BAT",
   "VENT AIRE CAL INF PRESECADO",
   "VENT AIRE ENF MANDOS SECADORES",
   "VENT EXTRACTOR CAPOTA 2° BAT",
   "VENT AIRE CAL 1° y 2° BAT",
   "VENT EXTRACTOR CAPOTA 1° BAT"
  ]
 },
 "CINTAS BAJO MAQ": {
  "CINTA BAJO MAQ 1": [
   "ROLLOS CBM 1",
   "MANDO CBM 1",
   "TENSORES CBM 1",
   "TELA CBM 1",
   "ESTRUCTURA CBM 1",
   "GUIA TELA CBM 1"
  ],
  "CINTA BAJO MAQ 2": [
   "ROLLOS CBM 2",
   "MANDO CBM 2",
   "TENSORES CBM 2",
   "TELA CBM 2",
   "ESTRUCTURA CBM 2"
  ],
  "CINTA BAJO MAQ 3": [
   "ROLLOS CBM 3",
   "MANDO CBM 3",
   "TENSORES CBM 3",
   "TELA CBM 3",
   "ESTRUCTURA CBM 3"
  ],
  "CINTA BAJO MAQ 4": [
   "ROLLOS CBM 4",
   "MANDO CBM 4",
   "TENSORES CBM 4",
   "TELA CBM 4",
   "ESTRUCTURA CBM 4"
  ],
  "CINTA BAJO MAQ 5": [
   "ROLLOS CBM 5",
   "MANDO CBM 5",
   "TENSORES CBM 5",
   "TELA CBM 5",
   "ESTRUCTURA CBM 5"
  ],
  "CINTA BAJO MAQ 6": [
   "ROLLOS CBM 6",
   "MANDO CBM 6",
   "TENSORES CBM 6",
   "TELA CBM 6",
   "ESTRUCTURA CBM 6"
  ],
  "CINTA BAJO MAQ 7": [
   "ROLLOS CBM 7",
   "MANDO CBM 7",
   "TENSORES CBM 7",
   "TELA CBM 7",
   "ESTRUCTURA CBM 7"
  ],
  "CINTA BAJO MAQ 8": [
   "ROLLOS CBM 8",
   "MANDO CBM 8",
   "TENSORES CBM 8",
   "TELA CBM 8",
   "ESTRUCTURA CBM 8"
  ],
  "CINTA BAJO MAQ 9": [
   "ROLLOS CBM 9",
   "MANDO CBM 9",
   "TENSORES CBM 9",
   "TELA CBM 9",
   "ESTRUCTURA CBM 9"
  ]
 },
 "PULPER BAJO MAQUINA": {
  "PULPER BAJO MAQUINA": [
   "PULPER",
   "ROTOR 1 PBM",
   "ROTOR 2 PBM",
   "BOMBA PBM",
   "VALVULAS PBM",
   "REGADERAS PBM"
  ]
 },
 "ESTUCADO": {
  "UNI BAR": [
   "ESTUCADORA UNI BAR",
   "SOLARONIC UNI BAR",
   "VENT AIRE COMB MAXON 2 UNI BAR",
   "VENT AIRE RECIRC MAXON 2 UNI BAR",
   "VENT AIRE COMB SOLARONIC UNI BAR",
   "VENT RECIRC SOLARONIC UNI BAR",
   "CORREAS MANDO ROLLOS UNI BAR",
   "CONTRARODILLO UNI BAR",
   "ROLLO APLICADOR UNI BAR",
   "ROLLOS PAPEL UNI BAR",
   "MANDO M17 CONTRARODILLO UNI BAR",
   "MANDO ROLLO APLICADOR UNI BAR",
   "MANDOS ROLLOS PAPEL UNI BAR",
   "SOGA UNI BAR",
   "VARILLA UNI BAR"
  ],
  "CALANDRA 1": [
   "CALANDRA 1",
   "CENTRAL HIDRAULICA CALANDRA 1",
   "CUCHILLAS CALANDRA 1",
   "MANDO M14 CALANDRA 1",
   "ROLLO SUP KUSTER CALANDRA 1",
   "ROLLO INF CALANDRA 1",
   "TENSOR NEUM SOGA EXT CALANDRA 1",
   "TENSOR NEUM SOGA INT CALANDRA 1"
  ],
  "VARI BAR": [
   "ESTUCADORA VARI BAR",
   "VAPOR ESTUFAS VARI BAR",
   "VENT NA01 VARI BAR",
   "INTERCAMBIADOR NA01 VARI BAR",
   "MANDO M16 SOGA VARI BAR",
   "VARILLA VARI BAR",
   "CORREAS MANDO ROLLOS VARI BAR",
   "CONTRARODILLO VARI BAR",
   "ROLLO APLICADOR VARI BAR",
   "ROLLOS PAPEL VARI BAR",
   "MANDO M15 SOGAS VARI BAR",
   "MANDO M16 CONTRARODILLO VARI BAR",
   "MANDO ROLLO APLICADOR VARI BAR",
   "SOGA VARI BAR",
   "TENSOR NEUM SOGA EXT VARI BAR",
   "TENSOR NEUM SOGA INT VARI BAR"
  ],
  "LABIO SOPLADOR": [
   "ESTUCADORA LABIO SOPLADOR",
   "VAPOR ESTUFAS LABIO SOPLADOR",
   "SOLARONIC LABIO SOPLADOR",
   "CONTRARODILLO LABIO SOPLADOR",
   "INTERCAMBIADOR NB01 LABIO SOPLADOR",
   "ROLLO APLICADOR LABIO SOPLADOR",
   "ROLLO PREALISADOS LABIO SOPLADOR",
   "ROLLO SELLADOR CAJA LABIO SOPLADOR",
   "ROLLOS PAPEL LABIO SOPLADOR",
   "MANDO M19 SOGA LABIO SOPLADOR",
   "CORREAS MANDO ROLLOS LABIO SOPLADOR",
   "SOGA 1 LABIO SOPLADOR",
   "TENSOR NEUM SOGA 1 LABIO SOPLADOR",
   "SOGA 3 LABIO SOPLADOR",
   "TENSOR NEUM SOGA 3 LABIO SOPLADOR",
   "VENT AIRE COMB SOLARONIC LABIO SOPLADOR",
   "VENT RECIRC SOLARONIC LABIO SOPLADOR",
   "VENT NB01 LABIO SOPLADOR",
   "SOPLADOR LABIO SOPLADOR",
   "VENT EXTRACTOR POLVILLO LABIO SOPLADOR"
  ],
  "COMBI BLADE": [
   "ESTUCADORA COMBI BLADE",
   "SOLARONIC COMBI BLADE",
   "CORREAS MANDO ROLLOS COMBI BLADE",
   "CONTRARODILLO COMBI BLADE",
   "MANDO M21 SOGAS COMBI BLADE",
   "MANDO ROLLO APLICADOR COMBI BLADE",
   "MANDO CONTRARODILLO COMBI BLADE",
   "ROLLO APLICADOR COMBI BLADE",
   "ROLLOS PAPEL COMBI BLADE",
   "TENSOR NEUM SOGA EXT COMBI BLADE",
   "TENSOR NEUM SOGA INT COMBI BLADE",
   "VARILLA COMBI BLADE",
   "VENT AIRE COMB MAXON 1 COMBI BLADE",
   "VENT AIRE RECIRC MAXON 1 COMBI BLADE",
   "VENT AIRE COMB SOLARONIC COMBI BLADE",
   "VENT AIRE RECIRC SOLARONIC COMBI BLADE"
  ],
  "SOTANO ESTUCADO": [
   "ESTACION FINAL UNI BAR",
   "AGITADOR ESTACION FINAL F3 UNI BAR",
   "ZARANDA ESTACION FINAL F3 UNI BAR",
   "BOMBA PF3 ESTACION FINAL UNI BAR",
   "ESTACION FINAL VARI BAR",
   "AGITADOR ESTACION FINAL F1 VARI BAR",
   "ZARANDA ESTACION FINAL F1 VARI BAR",
   "BOMBA PF1 ESTACION FINAL VARI BAR",
   "ESTACION FINAL LABIO SOPLADOR",
   "AGITADOR ESTACION FINAL F2 LABIO SOPLADOR",
   "ZARANDA ESTACION FINAL F2 LABIO SOPLADOR",
   "BOMBA PF2 ESTACION FINAL LABIO SOPLADOR",
   "ESTACION FINAL COMBI BLADE",
   "AGITADOR ESTACION FINAL PF4 COMBI BLADE",
   "ZARANDA ESTACION FINAL F4 COMBI BLADE",
   "BOMBA PF4 ESTACION FINAL COMBI BLADE",
   "BOMBA RECUPERO SALSA ESTACION FINAL COMBI BLADE",
   "FILTROS RONNINGER PETER COMBI BLADE"
  ]
 },
 "SEXTA BATERIA": {
  "ENFRIADORES": [
   "MANDO ENFRIADORES",
   "ENFRIADOR E1",
   "ENFRIADOR E2",
   "BOMBA RECUPERO AGUA ENFRIADORES"
  ],
  "CALANDRA 2": [
   "CALANDRA 2",
   "CUCHILLAS CALANDRA 2",
   "MANDO CALANDRA 2"
  ]
 },
 "POPE": {
  "POPE": [
   "ENROLLADORA POPE",
   "PUENTE GRUA 10T POPE",
   "BARRAS BOBINAS POPE",
   "CILINDRO ENROLLADORA POPE",
   "CILINDROS NEUMATICOS POPE",
   "CUCHILLA CILINDRO ENROLLADORA POPE",
   "MANDO POPE",
   "TENSOR NEU SOGA EXT POPE",
   "TENSOR NEU SOGA INT POPE",
   "ROLLO BANANA POPE",
   "ACELERADOR DE BARRA POPE",
   "TUSA POPE",
   "ESCANER VALMET"
  ]
 },
 "CELLIER": {
  "CELLIER": [
   "AGITADOR TQ B1",
   "AGITADOR TQ COCINADOR C1",
   "AGITADOR TQ COCINADOR C2",
   "AGITADORES TANQUES E",
   "BOMBA B1 AGUA SELLO DILUTORES",
   "BOMBA B2 AGUA SELLO DILUTORES",
   "BOMBA TQ E1 Y E2",
   "BOMBA TQ E4 Y E5",
   "BOMBA TQ E6",
   "BOMBA TQ E7",
   "DILUTOR 1",
   "DILUTOR 2",
   "DILUTOR 3",
   "MONTACARGAS CELLIER",
   "SOPLADOR TRANSPORTE CAOLIN",
   "VAPOR CELLIER",
   "VENT EXTRACTOR DILUTORES 2 Y 3"
  ]
 },
 "ALISTAMIENTO": {
  "REBOBINADORA": [
   "ACOPLE BOBINA MADRE",
   "APRETACANOS REBOBINADORA",
   "CILINDROS NEUMATICOS REBOBINADORA",
   "FRENO BOBINA MADRE REBOBINADORA",
   "MANDOS REBOBINADORA",
   "REBOBINADORA",
   "ROLLOS REBOBINADORA",
   "VENT EXTRACTOR POLVILLO AXIAL REBOBINADORA",
   "VENT EXTRACTOR POLVILLO CENTRIFUGO REBOBINADORA",
   "VENT MOTORES MANDO REBOBINADORA"
  ],
  "PULPER REFILE REBOBINADORA": [
   "BOMBA PULPER REFILE",
   "MANDO PULPER REFILE",
   "PULPER REFILE",
   "VENT EXTRACTOR REFILE REBOBINADORA"
  ],
  "VOLCADOR DE BOBINAS": [
   "CILINDORS HIDRAULICOS VOLCADOR DE BOBINAS",
   "CENTRAL HIDRAULICA VOLCADOR DE BOBINAS",
   "CAJAS RODAMIENTO VOLCADOR DE BOBINAS",
   "MANDO MOVIMIENTO ROLLOS VOLCADOR DE BOBINAS"
  ]
 }
};
